### ISSUE TITLE
A question of render.cs

### ISSUE THREAD

**Issue by UMR19** [m-schuetz/compute_rasterizer#10]
![image](https://user-images.githubusercontent.com/100742005/170468625-6a40b3c9-e330-471f-a127-2d23438c9d7d.png)
in render.cs there's vec2 variable called imgPos, i don't know why it times 0.5 and plus 0.5, what does it mean?
Thank you very much if you can answer my questions. : )

**Comment by m-schuetz** [comment]
At this point, x and y are in normalized device coordinates, i.e., between -1 and 1. We need them between 0 and 1, then multiply them by the image size to get the pixel coordinates.

**Comment by UMR19** [comment]
thanks for your answer,  I finally know the meaning of this. :)
