### ISSUE TITLE
Problems building the project in VS 2022

### ISSUE THREAD

**Issue by trsh** [m-schuetz/compute_rasterizer#12]
![2022-12-19_120828](https://user-images.githubusercontent.com/3727523/208401088-4d200989-1dee-466f-a879-fb28c0205d19.png)

**Comment by trsh** [comment]
I managed a way around this, but it doesn't seem right and very work-around-ish :)

**Comment by xianyuMeng** [comment]
> 

Hi,  I add "libs\lazip\" to the include path and this solve the error.

**Comment by trsh** [comment]
I still think this should be fixed :), so not closing

**Comment by m-schuetz** [comment]
Fixed, looks like I've neglected the debug build and forgot the laszip include in it. For good performance, you should switch to release mode, though!

**Comment by trsh** [comment]
Tnx. Unfortunately I won't be able to test for a while, so I am closing this.
