### ISSUE TITLE
invisible window

### ISSUE THREAD

**Issue by jagenjo** [m-schuetz/compute_rasterizer#2]
If I compile in DEBUG (VS2019) it crashes in void V8Helper::setupGL in this line:
setupV8GLExtBindings(tpl);

If I compile in RELEASE it compiles and the console shows no error but the windows is invisible, I can only see the console (and if I click keys I see them in the log).

I have a 1070

**Comment by m-schuetz** [comment]
Hi,

Do you have one or more monitors? If just one, try setting the ```window.x``` variable to 0 in load_pointcloud.js, then save the file with ctrl+s. Upon saving, the window will be moved to location 0. 

Not sure about the debug build issue - it's an issue that appeared a while ago and we weren't able to fix it.

**Comment by saltfishmx** [comment]
> If I compile in DEBUG (VS2019) it crashes in void V8Helper::setupGL in this line: setupV8GLExtBindings(tpl);
> 
> If I compile in RELEASE it compiles and the console shows no error but the windows is invisible, I can only see the console (and if I click keys I see them in the log).
> 
> I have a 1070

i have fixed the problem, if you want to see the winodw before you save with ctrl + s and you have only one monitor ,you should set the window.x to 0 in the file execute.js

**Comment by m-schuetz** [comment]
Closing because this repository now contains a complete rewrite.
