### ISSUE TITLE
No data shows

### ISSUE THREAD

**Issue by muyanchen-zen** [m-schuetz/compute_rasterizer#3]
After I pressed Ctrl+s ,the window shows as the picture :
![image](https://user-images.githubusercontent.com/47655810/134798208-ad2e173c-e726-4a35-b09f-1498c4e23e5a.png)

I have modified parameters : 
![image](https://user-images.githubusercontent.com/47655810/134798776-f0b90d40-c0bd-410e-a907-e4435ec28b3b.png)

**Comment by Lu-pin-an** [comment]
i have the same problem ,have you solved it?

**Comment by m-schuetz** [comment]
Can you upload the las file so that I can take a look at it?

**Comment by m-schuetz** [comment]
Closing this because this repository now contains a complete rewrite.
