### ISSUE TITLE
load_pointcloud.js is not executed？

### ISSUE THREAD

**Issue by zleisure** [m-schuetz/compute_rasterizer#5]
@m-schuetz 
load_pointcloud.js is not executed, why, what am I missing？Thanks
![2022-03-29 164143](https://user-images.githubusercontent.com/18457955/160572148-cbce69b7-64a0-46e4-acd9-d0a33f5814ed.png)

**Comment by zleisure** [comment]
solved

**Comment by zleisure** [comment]
close

**Comment by andybak** [comment]
@zleisure it's polite to share your solution ;-)

Someone might find this page in 3 years time and curse you for not passing on any details!

**Comment by zleisure** [comment]
@andybak  sorry
The solution author has stated
"Once you save "load_pointcloud.js" via ctrl+s, it will be executed, the window will be repositioned, and the point cloud will be loaded."
